name: Deploy Vue 3 to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1. 必须先安装 pnpm 环境
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8 # 或者写你本地对应的版本，如 9

      # 2. 设置 Node.js，并开启 pnpm 缓存
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      # 3. 使用 pnpm 安装依赖
      - name: Install dependencies
        run: pnpm install

      # 4. 打包项目
      - name: Build
        run: pnpm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
